import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import Providers from "@/components/providers";
import { ThemeSwitcher } from "./ThemeSwitcher";

const jakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus_jakarta_-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Yevox",
  description: "Generated by Yevox",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themeScript = `
  (function() {
    const themes = {
      grove:    { p: { h: "156", c: "0.118" }, s: { h: "104", c: "0.038" }, a: { h: "34", c: "0.132" } },
      harbor:   { p: { h: "224", c: "0.112" }, s: { h: "188", c: "0.044" }, a: { h: "42", c: "0.135" } },
      ember:    { p: { h: "24", c: "0.118" }, s: { h: "82", c: "0.035" }, a: { h: "188", c: "0.092" } },
      berry:    { p: { h: "350", c: "0.108" }, s: { h: "42", c: "0.04" }, a: { h: "170", c: "0.088" } },
      graphite: { p: { h: "250", c: "0.038" }, s: { h: "182", c: "0.03" }, a: { h: "32", c: "0.12" } }
    };

    const saved = localStorage.getItem('app-theme-choice') || 'grove';
    const theme = themes[saved] || themes.grove;
    
    const root = document.documentElement;
    root.style.setProperty('--p-hue', theme.p.h);
    root.style.setProperty('--p-chroma', theme.p.c);
    root.style.setProperty('--s-hue', theme.s.h);
    root.style.setProperty('--s-chroma', theme.s.c);
    root.style.setProperty('--a-hue', theme.a.h);
    root.style.setProperty('--a-chroma', theme.a.c);
  })()
`;
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body className={`${jakartaSans.variable} antialiased font-sans`}>
        <Providers>
          <SidebarProvider>
            <AppSidebar />
            <main className="flex min-h-screen min-w-0 w-full flex-col overflow-x-hidden bg-background">
              <header className="sticky top-0 z-30 flex min-w-0 items-center justify-between gap-3 border-b bg-yevox-white/95 p-3 backdrop-blur sm:p-4">
                <div className="flex min-w-0 items-center gap-2">
                  <SidebarTrigger />
                  <h1 className="hidden truncate text-sm font-semibold sm:block">
                    Dashboard
                  </h1>
                </div>
                <div className="shrink-0">
                  <ThemeSwitcher />
                </div>
              </header>

              {/* Conteúdo da Página */}
              <div className="mx-auto w-full min-w-0 max-w-7xl flex-1">
                {children}
              </div>
            </main>
          </SidebarProvider>
        </Providers>
      </body>
    </html>
  );
}
