import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { AppShell } from "@/components/app-shell";
import Providers from "@/components/providers";

const jakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus_jakarta_-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Yevox",
  description: "Generated by Yevox",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themeScript = `
  (function() {
    const themes = {
      grove:    { p: { h: "154", c: "0.132" }, s: { h: "182", c: "0.048" }, a: { h: "84", c: "0.145" } },
      harbor:   { p: { h: "226", c: "0.128" }, s: { h: "194", c: "0.052" }, a: { h: "38", c: "0.148" } },
      vault:    { p: { h: "204", c: "0.102" }, s: { h: "168", c: "0.044" }, a: { h: "128", c: "0.118" } },
      sentinel: { p: { h: "238", c: "0.092" }, s: { h: "214", c: "0.032" }, a: { h: "178", c: "0.096" } },
      graphite: { p: { h: "265", c: "0.052" }, s: { h: "220", c: "0.026" }, a: { h: "174", c: "0.108" } }
    };

    const saved = localStorage.getItem('app-theme-choice') || 'grove';
    const theme = themes[saved] || themes.grove;
    const displayMode = localStorage.getItem('app-display-mode') === 'night' ? 'night' : 'light';
    
    const root = document.documentElement;
    root.classList.toggle('dark', displayMode === 'night');
    root.style.colorScheme = displayMode === 'night' ? 'dark' : 'light';
    root.style.setProperty('--p-hue', theme.p.h);
    root.style.setProperty('--p-chroma', theme.p.c);
    root.style.setProperty('--s-hue', theme.s.h);
    root.style.setProperty('--s-chroma', theme.s.c);
    root.style.setProperty('--a-hue', theme.a.h);
    root.style.setProperty('--a-chroma', theme.a.c);
  })()
`;

  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body className={`${jakartaSans.variable} antialiased font-sans`}>
        <Providers>
          <AppShell>{children}</AppShell>
        </Providers>
      </body>
    </html>
  );
}
